name: Insider Alerts
on:
  schedule:
    - cron: '30 19 * * 1-5'
    - cron: '0 13 * * 1-5'
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      - name: Run alerts bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MIN_BUY_USD: '100000'
          ROLE_KEYWORDS: 'CEO,CFO,Director'
          ALERT_SCORE: '9'
          ACCOUNT_EQUITY: '10000'
          RISK_FRAC: '0.005'
        run: python alerts_bot.py

      - name: Save state
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bot-state
          path: |
            alerts_sent.json
            positions.json
          if-no-files-found: ignore
