name: Insider Alerts
on:
  schedule:
    - cron: "30 19 * * 1-5"   # 19:30 London, Mon–Fri
    - cron: "0 13 * * 1-5"    # 13:00 London, Mon–Fri
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
  - uses: actions/checkout@v4

  - uses: actions/setup-python@v5
    with:
      python-version: "3.11"

  - name: Show files (sanity)
    run: |
      pwd
      ls -lah
      python --version

  - name: Upgrade pip and install deps
    run: |
      python -m pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
      pip freeze | tail -n 50

  - name: Run alerts bot (verbose)
    run: |
      set -x
      python -u alerts_bot.py

  - name: Save state (ignore if missing)
    if: always()
    uses: actions/upload-artifact@v4
    with:
      name: bot-state
      path: |
        alerts_sent.json
        positions.json
      if-no-files-found: ignore
